name: angiepeteyowell
favicon: null
layout_spectrum: 0.2731734055560082
typography_spectrum: 0.5359702177811414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7639899177011102
  lightness: 0.3020808796864003
  saturation: 0.08883329690434039
  rhythmicContrast: 0.1178886282723397
purpose: []
